[package]
name = "lua_discord_game_sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
discord_game_sdk = "1.0.1"
mlua = {version = "0.9.9",features = ["luajit", "module"]}
